### ISSUE TITLE
error booting server after install

### ISSUE THREAD

**Issue by gilfuser** [byulparan/LinkUGen#4]
Hi.
I'm using Linux Ubuntu Studio 16.10, SuperCollider 3.9dev.
I went to the building process and got an error when I tried to boot the server:

```
*** ERROR: dlopen '/usr/local/share/SuperCollider/Extensions/LinkUGen/Link.so' err '/usr/local/share/SuperCollider/Extensions/LinkUGen/Link.so: undefined symbol: __atomic_is_lock_free'
RESULT = 0
```
... and the server won't boot.

Bests,
Gil

**Comment by gilfuser** [comment]
OK!
I got it!

After

`$ export CXX="if not on OSX, set your C++ compiler. I recommend clang++ higher than 3.6. I failed to build it with g++ in Linux"`

Instead of `cmake .` i did:
`cmake -DSC_PATH="/usr/local/include/SuperCollider/" ..`

Now its working fine!

**Comment by mouser1** [comment]
Hi Gil,

I had exactly the same issue, but running SC 3.8.0 and running with your suggested change above I get the same result.

> *** ERROR: dlopen '/home/mitch/.local/share/SuperCollider/Extensions/LinkUGen/Link.so' err '/home/mitch/.local/share/SuperCollider/Extensions/LinkUGen/Link.so: undefined symbol: __atomic_is_lock_free'
>RESULT = 0
>ERROR: server failed to start

Would you, or anyone else, have any suggestions on how to fix this?

**Comment by gilfuser** [comment]
Hi mouser1,

I got it to work. I can't remember now how. Later today I'll check it and
post it here.

mouser1 <notifications@github.com> schrieb am So., 1. Okt. 2017 um
22:28 Uhr:

**Comment by mouser1** [comment]
Thanks very much Gil.

Regards,
Mitch
________________________________

**Comment by gilfuser** [comment]
Hi @mouser1 
sorry about the delay
The problem might be that you are pointing to the wrong directory.
Try to find where the file SCVersion.txt lives. This is the directory you need to point to. In my system is /usr/local/include/SuperCollider/
I found this here: [Installing-SuperCollider-on-Ubuntu-systems installing-the-plugins](https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-on-Ubuntu-systems#installing-the-plugins)

bests,
Gil

**Comment by mouser1** [comment]
Gil,

Thanks for the response.  I know my acknowledgement was overdue.  I believe i did this correctly but I will check again.  Should the symbol "atomic_is_lock_free" be in one of the SuperCollider .h libraries?  You are using 3.9dev I believe and I am using 3.8. Hopefully there is no difference.  Thanks again.

Regards,
Mitch

Regards,
Mitch
________________________________

**Comment by mouser1** [comment]
I started from scratch today and still have the same issue:

```
*** ERROR: dlopen '/home/mitch/.local/share/SuperCollider/Extensions/LinkUGen/Link.so' err '/home/mitch/.local/share/SuperCollider/Extensions/LinkUGen/Link.so: undefined symbol: __atomic_is_lock_free'
RESULT = 0
ERROR: server failed to start
```

Regards,
Mitch

**Comment by gilfuser** [comment]
Thats because you are still trying to install it in the Extensions folder.
Make a search in your computer to find the file SCVersion.txt. And point
the installation to that folder.

mouser1 <notifications@github.com> schrieb am Mi., 11. Okt. 2017 um
11:13 Uhr:

**Comment by mouser1** [comment]
Gil,

Here are the full instructions that I am performing:
```
$ cd /home/mitch/supercollider
$ git clone https://github.com/byulparan/LinkUGen.git
$ cd “/home/mitch/supercollider/LinkUGen”
$ export SC3_SRC="/home/mitch/supercollider/SuperCollider-Source/"
$ export LINK_SRC="/home/mitch/supercollider/link/"
$ export CXX="/usr/bin/clang++-4.0"
$ cmake -DSC_PATH="/usr/local/include/SuperCollider/" .
$ make
```
After the `cmake` command here is the output:
```
mitch@mitch-PD:LinkUGen$ cmake -DSC_PATH="/usr/local/include/SuperCollider/" .
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /home/mitch/anaconda3/bin/cc
-- Check for working C compiler: /home/mitch/anaconda3/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-4.0
-- Check for working CXX compiler: /usr/bin/clang++-4.0 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
SC3_SRC set to /home/mitch/supercollider/SuperCollider-Source/
LINK_SRC set to /home/mitch/supercollider/link/
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

  SC_PATH

-- Build files have been written to: /home/mitch/supercollider/LinkUGen
```
After running `make` the Link.so file gets generated and I move the resulting LinkUGen directory and all it's contents including the Classes folder to `/home/mitch/.local/share/SuperCollider/Extensions/` as per the instructions in the README.md file except there is no Link.scx file generated.

Can you identify what what steps I'm doing wrong?

Regards,
Mitch

**Comment by gilfuser** [comment]
Hey Mitch.
I had to reinstall the thing and noticed that I made a typo.
It should be 
`$ cmake -SC_PATH="/usr/local/include/SuperCollider/" . `
and not 
` -DSC_PATH=... `
But now it't not working anyways. I think for other reasons.

**Comment by mouser1** [comment]
Thanks Gil.  I was never able to get this to work. I’ll give it another whirl. It seems like you are having troubles as well now.

Mitch Kaufman
________________________________

**Comment by gilfuser** [comment]
Hi again Mitch
Forget what I wrote before and just do `sudo make` instead of just `make` at the end of the instructions. I think that's it.

**Comment by byulparan** [comment]
sorry for very late reply. I don't have Linux Machine, so I could not resolve this issue.
but 'undefined symbol: __atomic_is_lock_free'  seems build toolchain problem.
please report 
```
$ ldd LinkUgen/Link.so
```

I will fix CMakeLists.txt today.

**Comment by byulparan** [comment]
I update CMakeLists.txt now. 
please cleanup LinkUGen and rebuild it.

/ps/ you should be run in SC3.9.

**Comment by mouser1** [comment]
Park, Gil,

It looks like I got this to build correctly and it appears to be running correctly in SC3.9.  I haven't tried it yet with Ableton but will do so later.  Thanks for taking a look at this again and making the changes.  I appreciate it.

Regards,
Mitch
________________________________

**Comment by gilfuser** [comment]
I'm closing the issue with the comment that it should be add in the documentation that Linux users should 'sudo make' instead of just 'make'
